leonardo/ft3215_controller_a:
  ros__parameters:
    interface_name: position
    coefficient: 1.0
    joints:
      - joint_ft_11_12
      - joint_ft_12_13
      - joint_ft_13_14
    interfaces:
      - fd_left_ee_controller/ee/roll
      - fd_left_ee_controller/ee/pitch
      - fd_left_ee_controller/ee/yaw
      - fd_right_ee_controller/ee/roll
      - fd_right_ee_controller/ee/pitch
      - fd_right_ee_controller/ee/yaw
    pedal_state_topic: /leonardo/pedal_state

leonardo/ft3215_controller_b:
  ros__parameters:
    interface_name: position
    coefficient: 1.0
    joints:
      - joint_ft_14_15
      - joint_ft_15_16
      - joint_ft_16_17
    interfaces:
      - fd_left_ee_controller/ee/roll
      - fd_left_ee_controller/ee/pitch
      - fd_left_ee_controller/ee/yaw
      - fd_right_ee_controller/ee/roll
      - fd_right_ee_controller/ee/pitch
      - fd_right_ee_controller/ee/yaw
    pedal_state_topic: /leonardo/pedal_state