leonardo/fd_left_ee_controller:
  ros__parameters:
    transform_translation: [0.0, 0.0, 0.0]
    transform_rotation: [0.0, 0.0, 0.0]
    joints:
      - fd_left_x
      - fd_left_y
      - fd_left_z
      - fd_left_roll
      - fd_left_pitch
      - fd_left_yaw
    buttons:
      - fd_left_button

leonardo/fd_right_ee_controller:
  ros__parameters:
    transform_translation: [0.0, 0.0, 0.0]
    transform_rotation: [0.0, 0.0, 0.0]
    joints:
      - fd_right_x
      - fd_right_y
      - fd_right_z
      - fd_right_roll
      - fd_right_pitch
      - fd_right_yaw
    buttons:
      - fd_right_button