# ==============================================================================
# Controller Manager
# ==============================================================================
mtm_controllers/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    # joint state broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    # Left arm
    fd_left_effort_controller:
      type: effort_controllers/JointGroupEffortController
    fd_left_ee_broadcaster:
      type: mtm_controllers/FDLeftEePoseBroadcaster
    # Right arm
    fd_right_effort_controller:
      type: effort_controllers/JointGroupEffortController
    fd_right_ee_broadcaster:
      type: mtm_controllers/FDRightEePoseBroadcaster

# ==============================================================================
# Left controller params
# ==============================================================================
mtm_controllers/fd_left_effort_controller:
  ros__parameters:
    joints:
      - fd_left_x
      - fd_left_y
      - fd_left_z
      - fd_left_roll
      - fd_left_pitch
      - fd_left_yaw
#      - fd_left_gripper
mtm_controllers/fd_left_ee_broadcaster:
  ros__parameters:
    transform_translation:
      - 0.0
      - 0.0
      - 0.0
    transform_rotation:
      - 0.0
      - 0.0
      - 0.0
    joints:
      - fd_left_x
      - fd_left_y
      - fd_left_z
      - fd_left_roll
      - fd_left_pitch
      - fd_left_yaw
    buttons:
      - fd_left_button

# ==============================================================================
# Right controller params
# ==============================================================================
mtm_controllers/fd_right_effort_controller:
  ros__parameters:
    joints:
      - fd_right_x
      - fd_right_y
      - fd_right_z
      - fd_right_roll
      - fd_right_pitch
      - fd_right_yaw
#      - fd_right_gripper
mtm_controllers/fd_right_ee_broadcaster:
  ros__parameters:
    transform_translation:
      - 0.0
      - 0.0
      - 0.0
    transform_rotation:
      - 0.0
      - 0.0
      - 0.0
    joints:
      - fd_right_x
      - fd_right_y
      - fd_right_z
      - fd_right_roll
      - fd_right_pitch
      - fd_right_yaw
    buttons:
      - fd_right_button
