leonardo/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fd_left_ee_controller:
      type: mtm_controllers/FDLeftEeController

    fd_right_ee_controller:
      type: mtm_controllers/FDRightEeController

    ft3215_controller:
      type: psm_controllers/FT3215Controller